language: generic
sudo: require
os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex dppy_paper.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  file: tex/dppy_paper.pdf
  on:
    repo: guilgautier/DPPy_paper
    tags: true
  api-key:
    secure: C6paZpxR+WjiB6Sw2FUj7h+MHfvgc+O/NPSfruDyRkEtdumKrZimR2t3+vhew4ctHSTKMYEARgSZm2dhlBA3wsgTpCOoeX4lB/8dAxQKeaWiWVOX2nNNsiCcVtvJgfpsNJuBpYec129U8tuwwj173EydWqsJYYgK1EdMsCylYLbU8LPRiAuDxBJ8VbIeFQl6dni93wA33/51yHbVFwUHRttHtLv9T04708RUgNrNA0HB/hm5Wib/mz0DO/6IoImmiecnhLQAFLfj1mCOo5S5YyoADopjD3bfqR7WAABmObbfyKK3LVmaf271pItjbFiS3BqezI0PeCyh8M/MHzqFxZCSOcoe7EZ950jCR4AMX0zvGIEXt1vCSUL7hOEMgYBbEnI8JQ3waspr0KD3RiRGY3HUKhgCrsteeBY4rdtwPLvCUhDkw6KuyuQY61/EJNzwhXJrETcbXfWYpzoWx5EVi+6VlmWoBoETI7c5Ajz6mJR2KPT3ZAm2mh/ct3TL0Dvn8e3PBaDL9h7ZWrN/UW67xRGU1iLzkt9Zb9v7LeAPvVhd2i5kvpOrdJqkoDLOoj0MntUd9OW1vo8OWuFvITblyoEOEDv8dWGVhnnGVRoYqQ6aBpuGtjZlxzQLJ+piodLnvwnxb3072lKrtU0qx5pQYRomNhSnlkX/I+7Ij16LDP0=
