language: generic

sudo: require

matrix:
  include:
  - os: linux
    python: 3.4

install:
  # For LaTeX
  - ". ./scripts/ensure_latex.sh"
  - "./scripts/ensure_book_dependencies.sh"
  # To use minted package, install pygments toolbox
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install .

script:
- cd tex
- pdflatex --shell-escape dppy_paper.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ####
  file: tex/dppy_paper.pdf
  on:
    repo: guilgautier/DPPy_paper
    tags: true
