language: generic
sudo: require
matrix:
  include:
  - os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex dppy_paper.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ####
  file: tex/dppy_paper.pdf
  on:
    repo: guilgautier/DPPy_paper
    tags: true
